//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Course {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Course() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.Course", typeof(Course).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add course.
        /// </summary>
        public static string btnAddCourse {
            get {
                return ResourceManager.GetString("btnAddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add unit.
        /// </summary>
        public static string btnAddCourseUnit {
            get {
                return ResourceManager.GetString("btnAddCourseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete course.
        /// </summary>
        public static string btnConfirmDelete {
            get {
                return ResourceManager.GetString("btnConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to question.
        /// </summary>
        public static string btnCourseQuestionReply {
            get {
                return ResourceManager.GetString("btnCourseQuestionReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string btnCourseunit {
            get {
                return ResourceManager.GetString("btnCourseunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unit.
        /// </summary>
        public static string btnDeleteCourseUnit {
            get {
                return ResourceManager.GetString("btnDeleteCourseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit unit.
        /// </summary>
        public static string btnEditCourseUnit {
            get {
                return ResourceManager.GetString("btnEditCourseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save order.
        /// </summary>
        public static string btnSaveUnitOrder {
            get {
                return ResourceManager.GetString("btnSaveUnitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnUnitClose {
            get {
                return ResourceManager.GetString("btnUnitClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string btnUnitNotes {
            get {
                return ResourceManager.GetString("btnUnitNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save notes.
        /// </summary>
        public static string btnUnitNoteSave {
            get {
                return ResourceManager.GetString("btnUnitNoteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View existing questions.
        /// </summary>
        public static string btnViewExistingQuestion {
            get {
                return ResourceManager.GetString("btnViewExistingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Reply questions.
        /// </summary>
        public static string btnViewQuestionAsked {
            get {
                return ResourceManager.GetString("btnViewQuestionAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string fldCategory {
            get {
                return ResourceManager.GetString("fldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string fldCertificate {
            get {
                return ResourceManager.GetString("fldCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (minutes).
        /// </summary>
        public static string fldCourseDurationInMin {
            get {
                return ResourceManager.GetString("fldCourseDurationInMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        public static string fldCourseFees {
            get {
                return ResourceManager.GetString("fldCourseFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee type.
        /// </summary>
        public static string fldCourseFeeStatus {
            get {
                return ResourceManager.GetString("fldCourseFeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload content.
        /// </summary>
        public static string fldCourseFileUrl {
            get {
                return ResourceManager.GetString("fldCourseFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name.
        /// </summary>
        public static string fldCourseName {
            get {
                return ResourceManager.GetString("fldCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New question.
        /// </summary>
        public static string fldCourseNewQuestion {
            get {
                return ResourceManager.GetString("fldCourseNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string fldCourseQuestion {
            get {
                return ResourceManager.GetString("fldCourseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string fldCourseQuestionAns {
            get {
                return ResourceManager.GetString("fldCourseQuestionAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course state.
        /// </summary>
        public static string fldCourseState {
            get {
                return ResourceManager.GetString("fldCourseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string fldCourseStateComment {
            get {
                return ResourceManager.GetString("fldCourseStateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course type.
        /// </summary>
        public static string fldCourseType {
            get {
                return ResourceManager.GetString("fldCourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit name.
        /// </summary>
        public static string fldCourseUnitName {
            get {
                return ResourceManager.GetString("fldCourseUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course description.
        /// </summary>
        public static string fldDescription {
            get {
                return ResourceManager.GetString("fldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile compatible.
        /// </summary>
        public static string fldIsMobile {
            get {
                return ResourceManager.GetString("fldIsMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string fldMandatory {
            get {
                return ResourceManager.GetString("fldMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification option.
        /// </summary>
        public static string fldModificationOption {
            get {
                return ResourceManager.GetString("fldModificationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass mark (%).
        /// </summary>
        public static string fldPassMarks {
            get {
                return ResourceManager.GetString("fldPassMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date.
        /// </summary>
        public static string fldRequestDate {
            get {
                return ResourceManager.GetString("fldRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sco label.
        /// </summary>
        public static string fldScoLabel {
            get {
                return ResourceManager.GetString("fldScoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string fldStatus {
            get {
                return ResourceManager.GetString("fldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string fldTags {
            get {
                return ResourceManager.GetString("fldTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio delay (seconds).
        /// </summary>
        public static string fldUnitAudioContent {
            get {
                return ResourceManager.GetString("fldUnitAudioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit content.
        /// </summary>
        public static string fldUnitContent {
            get {
                return ResourceManager.GetString("fldUnitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit order.
        /// </summary>
        public static string fldUnitOrder {
            get {
                return ResourceManager.GetString("fldUnitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit source.
        /// </summary>
        public static string fldUnitPathURL {
            get {
                return ResourceManager.GetString("fldUnitPathURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type.
        /// </summary>
        public static string fldUnitType {
            get {
                return ResourceManager.GetString("fldUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window type.
        /// </summary>
        public static string fldUserDefined {
            get {
                return ResourceManager.GetString("fldUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window height.
        /// </summary>
        public static string fldWindowheight {
            get {
                return ResourceManager.GetString("fldWindowheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window width.
        /// </summary>
        public static string fldWindowwidth {
            get {
                return ResourceManager.GetString("fldWindowwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve course request.
        /// </summary>
        public static string lblApproveCourseRequest {
            get {
                return ResourceManager.GetString("lblApproveCourseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change courses state.
        /// </summary>
        public static string lblChangeCourseState {
            get {
                return ResourceManager.GetString("lblChangeCourseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete course?.
        /// </summary>
        public static string lblConfirmDeleteHeading {
            get {
                return ResourceManager.GetString("lblConfirmDeleteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete course unit?.
        /// </summary>
        public static string lblConfirmUnitDeleteHeading {
            get {
                return ResourceManager.GetString("lblConfirmUnitDeleteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing questions to display .
        /// </summary>
        public static string lblCourseNoQuestions {
            get {
                return ResourceManager.GetString("lblCourseNoQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question list.
        /// </summary>
        public static string lblCourseQuestionList {
            get {
                return ResourceManager.GetString("lblCourseQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have doubt in mind? Ask questions to Instructor.
        /// </summary>
        public static string lblCourseRaiseQuestion {
            get {
                return ResourceManager.GetString("lblCourseRaiseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course state.
        /// </summary>
        public static string lblCourseState {
            get {
                return ResourceManager.GetString("lblCourseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom course.
        /// </summary>
        public static string lblCustomCourse {
            get {
                return ResourceManager.GetString("lblCustomCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit course attributes.
        /// </summary>
        public static string lblEditCourseAttributes {
            get {
                return ResourceManager.GetString("lblEditCourseAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark unit as complete.
        /// </summary>
        public static string lblMarkUnitComplete {
            get {
                return ResourceManager.GetString("lblMarkUnitComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string lblQuestionStatePending {
            get {
                return ResourceManager.GetString("lblQuestionStatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replied.
        /// </summary>
        public static string lblQuestionStateReplied {
            get {
                return ResourceManager.GetString("lblQuestionStateReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCORM 1.2.
        /// </summary>
        public static string lblScorm12 {
            get {
                return ResourceManager.GetString("lblScorm12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected assessment.
        /// </summary>
        public static string lblSelectedUnitAssessment {
            get {
                return ResourceManager.GetString("lblSelectedUnitAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string lblUnitAssessment {
            get {
                return ResourceManager.GetString("lblUnitAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string lblUnitAudio {
            get {
                return ResourceManager.GetString("lblUnitAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string lblUnitContent {
            get {
                return ResourceManager.GetString("lblUnitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio source.
        /// </summary>
        public static string lblUnitContentAudio {
            get {
                return ResourceManager.GetString("lblUnitContentAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblUnitDocument {
            get {
                return ResourceManager.GetString("lblUnitDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        public static string lblUnitNoMatchedFound {
            get {
                return ResourceManager.GetString("lblUnitNoMatchedFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblUnitNotes {
            get {
                return ResourceManager.GetString("lblUnitNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make notes.
        /// </summary>
        public static string lblUnitNotesHeading {
            get {
                return ResourceManager.GetString("lblUnitNotesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string lblUnitVideo {
            get {
                return ResourceManager.GetString("lblUnitVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web content.
        /// </summary>
        public static string lblUnitWebContent {
            get {
                return ResourceManager.GetString("lblUnitWebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAPI.
        /// </summary>
        public static string lblXAPI {
            get {
                return ResourceManager.GetString("lblXAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected course?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected course unit?.
        /// </summary>
        public static string msgConfirmUnitDelete {
            get {
                return ResourceManager.GetString("msgConfirmUnitDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course already exists.
        /// </summary>
        public static string msgCourseAlreadyExist {
            get {
                return ResourceManager.GetString("msgCourseAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are data associated with selected course. [{0}] can&apos;t be deleted..
        /// </summary>
        public static string msgDeleteCourse {
            get {
                return ResourceManager.GetString("msgDeleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course name already exist.
        /// </summary>
        public static string msgDupCourseName {
            get {
                return ResourceManager.GetString("msgDupCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio is too large, maximum allowed size is :.
        /// </summary>
        public static string msgErrAudioLarge {
            get {
                return ResourceManager.GetString("msgErrAudioLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid audio file. Supported formats are.
        /// </summary>
        public static string msgErrAudioNotSupport {
            get {
                return ResourceManager.GetString("msgErrAudioNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentis too large, maximum allowed size is :.
        /// </summary>
        public static string msgErrDocumentLarge {
            get {
                return ResourceManager.GetString("msgErrDocumentLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid document file. Supported formats are.
        /// </summary>
        public static string msgErrDocumentNotSupport {
            get {
                return ResourceManager.GetString("msgErrDocumentNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is not SCORM 1.2 compliant..
        /// </summary>
        public static string msgErrNotScormCompliant {
            get {
                return ResourceManager.GetString("msgErrNotScormCompliant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorm course is too large, maximum allowed size is : 200MB..
        /// </summary>
        public static string msgErrScormLarge {
            get {
                return ResourceManager.GetString("msgErrScormLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid scorm file. Supported formats are.
        /// </summary>
        public static string msgErrScormNotSupport {
            get {
                return ResourceManager.GetString("msgErrScormNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video is too large, maximum allowed size is :.
        /// </summary>
        public static string msgErrVideoLarge {
            get {
                return ResourceManager.GetString("msgErrVideoLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid video file. Supported formats are.
        /// </summary>
        public static string msgErrVideoNotSupport {
            get {
                return ResourceManager.GetString("msgErrVideoNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Course. Please upload only SCORM 1.2 compatible courses..
        /// </summary>
        public static string msgIncorrectVersion {
            get {
                return ResourceManager.GetString("msgIncorrectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Course.
        /// </summary>
        public static string msgInvalidCourse {
            get {
                return ResourceManager.GetString("msgInvalidCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sco label length cannot exceed 10 char..
        /// </summary>
        public static string msgMxlScoLabel {
            get {
                return ResourceManager.GetString("msgMxlScoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content package should not contain imsmanifest.xml.
        /// </summary>
        public static string msgNoManifiest {
            get {
                return ResourceManager.GetString("msgNoManifiest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package does not in valid format.
        /// </summary>
        public static string msgPacInvalidFormat {
            get {
                return ResourceManager.GetString("msgPacInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select certificate.
        /// </summary>
        public static string msgReqCertificate {
            get {
                return ResourceManager.GetString("msgReqCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter answer.
        /// </summary>
        public static string msgReqCourseAnswerText {
            get {
                return ResourceManager.GetString("msgReqCourseAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select course subject.
        /// </summary>
        public static string msgReqCourseCategory {
            get {
                return ResourceManager.GetString("msgReqCourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter course description.
        /// </summary>
        public static string msgReqCourseDesc {
            get {
                return ResourceManager.GetString("msgReqCourseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file to upload.
        /// </summary>
        public static string msgReqCourseFile {
            get {
                return ResourceManager.GetString("msgReqCourseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter course name.
        /// </summary>
        public static string msgReqCourseName {
            get {
                return ResourceManager.GetString("msgReqCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter question.
        /// </summary>
        public static string msgReqCourseQuestionText {
            get {
                return ResourceManager.GetString("msgReqCourseQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter comments..
        /// </summary>
        public static string msgReqCourseStateComment {
            get {
                return ResourceManager.GetString("msgReqCourseStateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter unit name.
        /// </summary>
        public static string msgReqCourseUnitName {
            get {
                return ResourceManager.GetString("msgReqCourseUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please search and select assessment to add.
        /// </summary>
        public static string msgReqUnitAssessment {
            get {
                return ResourceManager.GetString("msgReqUnitAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter content.
        /// </summary>
        public static string msgReqUnitContent {
            get {
                return ResourceManager.GetString("msgReqUnitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file to upload.
        /// </summary>
        public static string msgReqUnitFile {
            get {
                return ResourceManager.GetString("msgReqUnitFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter notes..
        /// </summary>
        public static string msgReqUnitNotes {
            get {
                return ResourceManager.GetString("msgReqUnitNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid URL.
        /// </summary>
        public static string msgReqUnitWebContentURL {
            get {
                return ResourceManager.GetString("msgReqUnitWebContentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid pass marks..
        /// </summary>
        public static string msgRngPassMarks {
            get {
                return ResourceManager.GetString("msgRngPassMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid height..
        /// </summary>
        public static string msgRngWindowheight {
            get {
                return ResourceManager.GetString("msgRngWindowheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid width..
        /// </summary>
        public static string msgRngWindowwidth {
            get {
                return ResourceManager.GetString("msgRngWindowwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass marks must be numbers only..
        /// </summary>
        public static string msgStrPassMarksNumeric {
            get {
                return ResourceManager.GetString("msgStrPassMarksNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window height must be numbers only..
        /// </summary>
        public static string msgStrWinHeightNumeric {
            get {
                return ResourceManager.GetString("msgStrWinHeightNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window width must be numbers only..
        /// </summary>
        public static string msgStrWinWidthNumeric {
            get {
                return ResourceManager.GetString("msgStrWinWidthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version found. Supported version is (1.1 - 1.2.7).
        /// </summary>
        public static string msgUnSupportedScrom {
            get {
                return ResourceManager.GetString("msgUnSupportedScrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content modification.
        /// </summary>
        public static string optContentModification {
            get {
                return ResourceManager.GetString("optContentModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string optFeeTypeFree {
            get {
                return ResourceManager.GetString("optFeeTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string optFeeTypePaid {
            get {
                return ResourceManager.GetString("optFeeTypePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail.
        /// </summary>
        public static string optFeeTypeTrail {
            get {
                return ResourceManager.GetString("optFeeTypeTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full modification.
        /// </summary>
        public static string optFullModification {
            get {
                return ResourceManager.GetString("optFullModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In review.
        /// </summary>
        public static string optInReview {
            get {
                return ResourceManager.GetString("optInReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string optMandatory {
            get {
                return ResourceManager.GetString("optMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximise.
        /// </summary>
        public static string optMaximise {
            get {
                return ResourceManager.GetString("optMaximise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string optMobileNo {
            get {
                return ResourceManager.GetString("optMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string optMobileYes {
            get {
                return ResourceManager.GetString("optMobileYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modification.
        /// </summary>
        public static string optNoModification {
            get {
                return ResourceManager.GetString("optNoModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string optOptional {
            get {
                return ResourceManager.GetString("optOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string optPublished {
            get {
                return ResourceManager.GetString("optPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to publish.
        /// </summary>
        public static string optReadyPublish {
            get {
                return ResourceManager.GetString("optReadyPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reday to review.
        /// </summary>
        public static string optReadyReview {
            get {
                return ResourceManager.GetString("optReadyReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string optRejected {
            get {
                return ResourceManager.GetString("optRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file.
        /// </summary>
        public static string optUnitLocalFile {
            get {
                return ResourceManager.GetString("optUnitLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string optUnitYouTube {
            get {
                return ResourceManager.GetString("optUnitYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined.
        /// </summary>
        public static string optUserDefined {
            get {
                return ResourceManager.GetString("optUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string thAction {
            get {
                return ResourceManager.GetString("thAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string thCategory {
            get {
                return ResourceManager.GetString("thCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string thCertificate {
            get {
                return ResourceManager.GetString("thCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string thCourse {
            get {
                return ResourceManager.GetString("thCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date asked.
        /// </summary>
        public static string thCourseQDateAsked {
            get {
                return ResourceManager.GetString("thCourseQDateAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string thCourseQuestion {
            get {
                return ResourceManager.GetString("thCourseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string thCourseQuestionState {
            get {
                return ResourceManager.GetString("thCourseQuestionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string thEmailAddress {
            get {
                return ResourceManager.GetString("thEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string thExpiryDate {
            get {
                return ResourceManager.GetString("thExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head / Manager&apos;s name.
        /// </summary>
        public static string thManager {
            get {
                return ResourceManager.GetString("thManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed users.
        /// </summary>
        public static string thMaxUserAllwoed {
            get {
                return ResourceManager.GetString("thMaxUserAllwoed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned users .
        /// </summary>
        public static string thNoOfUserAssigned {
            get {
                return ResourceManager.GetString("thNoOfUserAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string thOrganisation {
            get {
                return ResourceManager.GetString("thOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string thState {
            get {
                return ResourceManager.GetString("thState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string thStatus {
            get {
                return ResourceManager.GetString("thStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Youtube embed URL only.
        /// </summary>
        public static string tooltilYouEmbedURL {
            get {
                return ResourceManager.GetString("tooltilYouEmbedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create unit.
        /// </summary>
        public static string tooltipCreateUnit {
            get {
                return ResourceManager.GetString("tooltipCreateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder units.
        /// </summary>
        public static string tooltipReorderUnit {
            get {
                return ResourceManager.GetString("tooltipReorderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type min. 2 chars and select from list. Use Up/Down arrow to select..
        /// </summary>
        public static string tooltipUnitAssessmentSearch {
            get {
                return ResourceManager.GetString("tooltipUnitAssessmentSearch", resourceCulture);
            }
        }
    }
}
