//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Group {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Group() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.Group", typeof(Group).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string btnAddGroup {
            get {
                return ResourceManager.GetString("btnAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        public static string btnConfirmDelete {
            get {
                return ResourceManager.GetString("btnConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and preview.
        /// </summary>
        public static string btnH_pagePreview {
            get {
                return ResourceManager.GetString("btnH_pagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name exist..
        /// </summary>
        public static string errDupGroup {
            get {
                return ResourceManager.GetString("errDupGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact no..
        /// </summary>
        public static string fldGroupContactNo {
            get {
                return ResourceManager.GetString("fldGroupContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string fldGroupEmailId {
            get {
                return ResourceManager.GetString("fldGroupEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML content.
        /// </summary>
        public static string fldGroupHomePageContent {
            get {
                return ResourceManager.GetString("fldGroupHomePageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string fldGroupHomepageGroupName {
            get {
                return ResourceManager.GetString("fldGroupHomepageGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image position.
        /// </summary>
        public static string fldGroupHomepageImgPosition {
            get {
                return ResourceManager.GetString("fldGroupHomepageImgPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string fldGroupHomePageImgPositionOption1 {
            get {
                return ResourceManager.GetString("fldGroupHomePageImgPositionOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string fldGroupHomePageImgPositionOption2 {
            get {
                return ResourceManager.GetString("fldGroupHomePageImgPositionOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string fldGroupHomePageImgPositionOption3 {
            get {
                return ResourceManager.GetString("fldGroupHomePageImgPositionOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that all the couses with an  &apos;In progress&apos; or &apos;Not started&apos;  status will be displayed below the HTML content in alphabetical order. Please click on Preview button to preview the homepage and sample listing of courses.
        /// </summary>
        public static string fldGroupHomepageNote {
            get {
                return ResourceManager.GetString("fldGroupHomepageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string fldGroupHomepageOrgName {
            get {
                return ResourceManager.GetString("fldGroupHomepageOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image.
        /// </summary>
        public static string fldGroupHomePageUploadImage {
            get {
                return ResourceManager.GetString("fldGroupHomePageUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head / Manager&apos;s name.
        /// </summary>
        public static string fldGroupManagerName {
            get {
                return ResourceManager.GetString("fldGroupManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string fldGroupName {
            get {
                return ResourceManager.GetString("fldGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string fldOrganisationID {
            get {
                return ResourceManager.GetString("fldOrganisationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string fldStatus {
            get {
                return ResourceManager.GetString("fldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        public static string flsGroupDesc {
            get {
                return ResourceManager.GetString("flsGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course assignment basis.
        /// </summary>
        public static string lblAssigned {
            get {
                return ResourceManager.GetString("lblAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group?.
        /// </summary>
        public static string lblConfirmDeleteHeading {
            get {
                return ResourceManager.GetString("lblConfirmDeleteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string lblExpDate {
            get {
                return ResourceManager.GetString("lblExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max users.
        /// </summary>
        public static string lblMaxUsers {
            get {
                return ResourceManager.GetString("lblMaxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected group?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are data associated with selected group. [{0}] can&apos;t be deleted..
        /// </summary>
        public static string msgDeleteGroup {
            get {
                return ResourceManager.GetString("msgDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users can not be greater than .
        /// </summary>
        public static string msgErrorGreaterthan {
            get {
                return ResourceManager.GetString("msgErrorGreaterthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users should be a integer number only.
        /// </summary>
        public static string msgErrorIntegerOnly {
            get {
                return ResourceManager.GetString("msgErrorIntegerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group..
        /// </summary>
        public static string msgInvalidGroup {
            get {
                return ResourceManager.GetString("msgInvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group contact no length cannot exceed 50 char..
        /// </summary>
        public static string msgMxlGroupContactNo {
            get {
                return ResourceManager.GetString("msgMxlGroupContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description length cannot exceed 400 char..
        /// </summary>
        public static string msgMxlGroupDesc {
            get {
                return ResourceManager.GetString("msgMxlGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group email address length cannot exceed 256 char..
        /// </summary>
        public static string msgMxlGroupEmailId {
            get {
                return ResourceManager.GetString("msgMxlGroupEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group head/manager name length cannot exceed 100 char..
        /// </summary>
        public static string msgMxlGroupManager {
            get {
                return ResourceManager.GetString("msgMxlGroupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name length cannot exceed 100 char..
        /// </summary>
        public static string msgMxlGroupName {
            get {
                return ResourceManager.GetString("msgMxlGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users length cannot exceed 6 digit..
        /// </summary>
        public static string msgMxlMaxUser {
            get {
                return ResourceManager.GetString("msgMxlMaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter group description.
        /// </summary>
        public static string msgReqGroupDesc {
            get {
                return ResourceManager.GetString("msgReqGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter group home page content.
        /// </summary>
        public static string msgReqGroupHomePageContent {
            get {
                return ResourceManager.GetString("msgReqGroupHomePageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select group home page image location.
        /// </summary>
        public static string msgReqGroupHomePageImgPosition {
            get {
                return ResourceManager.GetString("msgReqGroupHomePageImgPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image file.
        /// </summary>
        public static string msgReqGroupHomePageUploadImage {
            get {
                return ResourceManager.GetString("msgReqGroupHomePageUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter group name.
        /// </summary>
        public static string msgReqGroupName {
            get {
                return ResourceManager.GetString("msgReqGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no. of users.
        /// </summary>
        public static string msgReqMaxUser {
            get {
                return ResourceManager.GetString("msgReqMaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a valid image file.
        /// </summary>
        public static string msgValGroupHomePageUploadImage {
            get {
                return ResourceManager.GetString("msgValGroupHomePageUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact no.
        /// </summary>
        public static string thContactNo {
            get {
                return ResourceManager.GetString("thContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string thEmailAddress {
            get {
                return ResourceManager.GetString("thEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string thGroup {
            get {
                return ResourceManager.GetString("thGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head / Manager&apos;s name.
        /// </summary>
        public static string thManager {
            get {
                return ResourceManager.GetString("thManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string thOrganisation {
            get {
                return ResourceManager.GetString("thOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string thStatus {
            get {
                return ResourceManager.GetString("thStatus", resourceCulture);
            }
        }
    }
}
