//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string fldConfirmPassword {
            get {
                return ResourceManager.GetString("fldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string fldCurrentpassword {
            get {
                return ResourceManager.GetString("fldCurrentpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string fldNewPassword {
            get {
                return ResourceManager.GetString("fldNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password and new password can not be same..
        /// </summary>
        public static string msgComplareOldPassword {
            get {
                return ResourceManager.GetString("msgComplareOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered and a mail has been sent to you with the following credentials:.
        /// </summary>
        public static string msgConfirmSelfRegistration {
            get {
                return ResourceManager.GetString("msgConfirmSelfRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string msgErrorConfirmPassword {
            get {
                return ResourceManager.GetString("msgErrorConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username / password..
        /// </summary>
        public static string msgErrorInvalidLogin {
            get {
                return ResourceManager.GetString("msgErrorInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string msgErrorNewPasswordLength {
            get {
                return ResourceManager.GetString("msgErrorNewPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organisation licence expired, please contact administrator..
        /// </summary>
        public static string msgErrorOrgLicExpired {
            get {
                return ResourceManager.GetString("msgErrorOrgLicExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mail with new password has been sent to you..
        /// </summary>
        public static string msgForgotConfirmPasswordmail {
            get {
                return ResourceManager.GetString("msgForgotConfirmPasswordmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong please try again later..
        /// </summary>
        public static string msgForgotPasswordError {
            get {
                return ResourceManager.GetString("msgForgotPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password.
        /// </summary>
        public static string msgReqConfirmPassword {
            get {
                return ResourceManager.GetString("msgReqConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter current password.
        /// </summary>
        public static string msgReqCurrentPassword {
            get {
                return ResourceManager.GetString("msgReqCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password.
        /// </summary>
        public static string msgReqNewPassword {
            get {
                return ResourceManager.GetString("msgReqNewPassword", resourceCulture);
            }
        }
    }
}
