//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Organisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.Organisation", typeof(Organisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organisation.
        /// </summary>
        public static string btnConfirmDelete {
            get {
                return ResourceManager.GetString("btnConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string dropOrganisation {
            get {
                return ResourceManager.GetString("dropOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select organisation--.
        /// </summary>
        public static string dropSelectOrg {
            get {
                return ResourceManager.GetString("dropSelectOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string fldAvailableGroupList {
            get {
                return ResourceManager.GetString("fldAvailableGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string fldLicExpDate {
            get {
                return ResourceManager.GetString("fldLicExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users.
        /// </summary>
        public static string fldLicMaxUsers {
            get {
                return ResourceManager.GetString("fldLicMaxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string fldLicOrganisation {
            get {
                return ResourceManager.GetString("fldLicOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string fldOrganisationAddress1 {
            get {
                return ResourceManager.GetString("fldOrganisationAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string fldOrganisationAddress2 {
            get {
                return ResourceManager.GetString("fldOrganisationAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        public static string fldOrganisationAddress3 {
            get {
                return ResourceManager.GetString("fldOrganisationAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select banner.
        /// </summary>
        public static string fldOrganisationbanner {
            get {
                return ResourceManager.GetString("fldOrganisationbanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string fldOrganisationCountry {
            get {
                return ResourceManager.GetString("fldOrganisationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation id.
        /// </summary>
        public static string fldOrganisationID {
            get {
                return ResourceManager.GetString("fldOrganisationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select logo.
        /// </summary>
        public static string fldOrganisationlogo {
            get {
                return ResourceManager.GetString("fldOrganisationlogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string fldOrganisationName {
            get {
                return ResourceManager.GetString("fldOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string fldOrganisationPostalCode {
            get {
                return ResourceManager.GetString("fldOrganisationPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string fldOrganisationStatus {
            get {
                return ResourceManager.GetString("fldOrganisationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow individual assignment.
        /// </summary>
        public static string lblAllowIndividualAssignment {
            get {
                return ResourceManager.GetString("lblAllowIndividualAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organisation?.
        /// </summary>
        public static string lblConfirmDeleteHeading {
            get {
                return ResourceManager.GetString("lblConfirmDeleteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group assignment.
        /// </summary>
        public static string lblGroupAssignment {
            get {
                return ResourceManager.GetString("lblGroupAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual assignment.
        /// </summary>
        public static string lblIndividualAssignment {
            get {
                return ResourceManager.GetString("lblIndividualAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid image file.
        /// </summary>
        public static string lblInvalidImageFile {
            get {
                return ResourceManager.GetString("lblInvalidImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected organisation?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are data associated with selected organisation. [{0}] can&apos;t be deleted..
        /// </summary>
        public static string msgDeleteOrganisation {
            get {
                return ResourceManager.GetString("msgDeleteOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation id already exist.
        /// </summary>
        public static string msgDupOrganisationID {
            get {
                return ResourceManager.GetString("msgDupOrganisationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name already exist.
        /// </summary>
        public static string msgDupOrganisationName {
            get {
                return ResourceManager.GetString("msgDupOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation licence already exists.
        /// </summary>
        public static string msgDupOrgLicence {
            get {
                return ResourceManager.GetString("msgDupOrgLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization max user can not less than no of user assigned to group of this organization.
        /// </summary>
        public static string msgErrOrganizationMaxUserIsLessthan {
            get {
                return ResourceManager.GetString("msgErrOrganizationMaxUserIsLessthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid organisation..
        /// </summary>
        public static string msgInvalidOrganisation {
            get {
                return ResourceManager.GetString("msgInvalidOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of users created for this organisation are greater than the number of users provided.
        /// </summary>
        public static string msgLicNoOfUserAlert {
            get {
                return ResourceManager.GetString("msgLicNoOfUserAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users must be greater than 0.
        /// </summary>
        public static string msgLicStrMaxUsersGtZero {
            get {
                return ResourceManager.GetString("msgLicStrMaxUsersGtZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users should be a whole number.
        /// </summary>
        public static string msgLicStrUsersWholeNumber {
            get {
                return ResourceManager.GetString("msgLicStrUsersWholeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation address 1 length cannot exceed 150 char..
        /// </summary>
        public static string msgMxlOrganisationAddress1 {
            get {
                return ResourceManager.GetString("msgMxlOrganisationAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation address 2 length cannot exceed 150 char..
        /// </summary>
        public static string msgMxlOrganisationAddress2 {
            get {
                return ResourceManager.GetString("msgMxlOrganisationAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation address 3 length cannot exceed 150 char..
        /// </summary>
        public static string msgMxlOrganisationAddress3 {
            get {
                return ResourceManager.GetString("msgMxlOrganisationAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation id length cannot exceed 50 char..
        /// </summary>
        public static string msgMxlOrganisationID {
            get {
                return ResourceManager.GetString("msgMxlOrganisationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name length cannot exceed 100 char..
        /// </summary>
        public static string msgMxlOrganisationName {
            get {
                return ResourceManager.GetString("msgMxlOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation postal code length cannot exceed 10 char..
        /// </summary>
        public static string msgMxlOrganisationPostalCode {
            get {
                return ResourceManager.GetString("msgMxlOrganisationPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation can be null. as this is the last group assigned to the organisation..
        /// </summary>
        public static string msgReqAtleastSelectOneGroup {
            get {
                return ResourceManager.GetString("msgReqAtleastSelectOneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter expiry date.
        /// </summary>
        public static string msgReqLicExpDate {
            get {
                return ResourceManager.GetString("msgReqLicExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no. of users.
        /// </summary>
        public static string msgReqLicMaxUsers {
            get {
                return ResourceManager.GetString("msgReqLicMaxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select organisation.
        /// </summary>
        public static string msgReqLicOrganisation {
            get {
                return ResourceManager.GetString("msgReqLicOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select organisation banner.
        /// </summary>
        public static string msgReqOrganisationbanner {
            get {
                return ResourceManager.GetString("msgReqOrganisationbanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation country length cannot exceed 50 char..
        /// </summary>
        public static string msgReqOrganisationCountry {
            get {
                return ResourceManager.GetString("msgReqOrganisationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one group.
        /// </summary>
        public static string msgReqOrganisationGroup {
            get {
                return ResourceManager.GetString("msgReqOrganisationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter organisation id.
        /// </summary>
        public static string msgReqOrganisationID {
            get {
                return ResourceManager.GetString("msgReqOrganisationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select organisation logo.
        /// </summary>
        public static string msgReqOrganisationlogo {
            get {
                return ResourceManager.GetString("msgReqOrganisationlogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter organisation name.
        /// </summary>
        public static string msgReqOrganisationName {
            get {
                return ResourceManager.GetString("msgReqOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users must be numbers only..
        /// </summary>
        public static string msgStrMaxUsersNumeric {
            get {
                return ResourceManager.GetString("msgStrMaxUsersNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string thCreatedDate {
            get {
                return ResourceManager.GetString("thCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string thExpiryDate {
            get {
                return ResourceManager.GetString("thExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string thGroups {
            get {
                return ResourceManager.GetString("thGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of users.
        /// </summary>
        public static string thNoOfUsers {
            get {
                return ResourceManager.GetString("thNoOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string thOrganisationAddress1 {
            get {
                return ResourceManager.GetString("thOrganisationAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string thOrganisationAddress2 {
            get {
                return ResourceManager.GetString("thOrganisationAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string thOrganisationCountry {
            get {
                return ResourceManager.GetString("thOrganisationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation id.
        /// </summary>
        public static string thOrganisationID {
            get {
                return ResourceManager.GetString("thOrganisationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name.
        /// </summary>
        public static string thOrganisationName {
            get {
                return ResourceManager.GetString("thOrganisationName", resourceCulture);
            }
        }
    }
}
