//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.ProfileSettings", typeof(ProfileSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Name.
        /// </summary>
        public static string fldBlockName {
            get {
                return ResourceManager.GetString("fldBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string fldDisplay {
            get {
                return ResourceManager.GetString("fldDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Name.
        /// </summary>
        public static string fldDistrictName {
            get {
                return ResourceManager.GetString("fldDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string fldEmailBody {
            get {
                return ResourceManager.GetString("fldEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string fldEmailIsOn {
            get {
                return ResourceManager.GetString("fldEmailIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From email.
        /// </summary>
        public static string fldFromEmail {
            get {
                return ResourceManager.GetString("fldFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Name.
        /// </summary>
        public static string fldGroupNames {
            get {
                return ResourceManager.GetString("fldGroupNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string fldGroupsName {
            get {
                return ResourceManager.GetString("fldGroupsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help content.
        /// </summary>
        public static string fldHelpModuleContent {
            get {
                return ResourceManager.GetString("fldHelpModuleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string FldisDisplayHelp {
            get {
                return ResourceManager.GetString("FldisDisplayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self registration.
        /// </summary>
        public static string FldisDisplaySelfReg {
            get {
                return ResourceManager.GetString("FldisDisplaySelfReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string fldMandatory {
            get {
                return ResourceManager.GetString("fldMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length.
        /// </summary>
        public static string fldMaxLength {
            get {
                return ResourceManager.GetString("fldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile title.
        /// </summary>
        public static string fldProfileTitle {
            get {
                return ResourceManager.GetString("fldProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile value.
        /// </summary>
        public static string fldProfileValuesTitle {
            get {
                return ResourceManager.GetString("fldProfileValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string fldSchoolName {
            get {
                return ResourceManager.GetString("fldSchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string fldSelfRegEmailAddress {
            get {
                return ResourceManager.GetString("fldSelfRegEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string fldSelfRegFirstName {
            get {
                return ResourceManager.GetString("fldSelfRegFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string fldSelfRegLastName {
            get {
                return ResourceManager.GetString("fldSelfRegLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string fldStudentName {
            get {
                return ResourceManager.GetString("fldStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string fldType {
            get {
                return ResourceManager.GetString("fldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Name.
        /// </summary>
        public static string fldUserNames {
            get {
                return ResourceManager.GetString("fldUserNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string fldUserType {
            get {
                return ResourceManager.GetString("fldUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve self registration.
        /// </summary>
        public static string lblApproveSelfReg {
            get {
                return ResourceManager.GetString("lblApproveSelfReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Users.
        /// </summary>
        public static string lblDenySelfRegUsers {
            get {
                return ResourceManager.GetString("lblDenySelfRegUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email management.
        /// </summary>
        public static string lblEmailManagement {
            get {
                return ResourceManager.GetString("lblEmailManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help configuration.
        /// </summary>
        public static string lblHelpConfig {
            get {
                return ResourceManager.GetString("lblHelpConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help management.
        /// </summary>
        public static string lblHelpManagement {
            get {
                return ResourceManager.GetString("lblHelpManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help setting.
        /// </summary>
        public static string lblHelpSetting {
            get {
                return ResourceManager.GetString("lblHelpSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence management.
        /// </summary>
        public static string lblLicenceManagement {
            get {
                return ResourceManager.GetString("lblLicenceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile values.
        /// </summary>
        public static string lblProfileValues {
            get {
                return ResourceManager.GetString("lblProfileValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email configuration.
        /// </summary>
        public static string lblSelfRegEmailConfig {
            get {
                return ResourceManager.GetString("lblSelfRegEmailConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self registration setting.
        /// </summary>
        public static string lblSelfRegSetting {
            get {
                return ResourceManager.GetString("lblSelfRegSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile values.
        /// </summary>
        public static string lblviewProfileValues {
            get {
                return ResourceManager.GetString("lblviewProfileValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are data associated with selected value. [{0}] can&apos;t be deleted..
        /// </summary>
        public static string msgDeleteProfileSettingsValues {
            get {
                return ResourceManager.GetString("msgDeleteProfileSettingsValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deny selected user(s)?.
        /// </summary>
        public static string msgDenySelfRegUsers {
            get {
                return ResourceManager.GetString("msgDenySelfRegUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile values already exist.
        /// </summary>
        public static string msgDupProfileValues {
            get {
                return ResourceManager.GetString("msgDupProfileValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all the values on form.
        /// </summary>
        public static string msgErrorProfileSettings {
            get {
                return ResourceManager.GetString("msgErrorProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxlength should be numeric.
        /// </summary>
        public static string msgErrorProfileSettingsNumeric {
            get {
                return ResourceManager.GetString("msgErrorProfileSettingsNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxlength should be between 1 and 100.
        /// </summary>
        public static string msgErrorProfileSettingsRange {
            get {
                return ResourceManager.GetString("msgErrorProfileSettingsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxlength should be Integer.
        /// </summary>
        public static string msgErrorProfileSettingsWhole {
            get {
                return ResourceManager.GetString("msgErrorProfileSettingsWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user profile value..
        /// </summary>
        public static string msgInvalidProfileSettingsValue {
            get {
                return ResourceManager.GetString("msgInvalidProfileSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid self registration detail.
        /// </summary>
        public static string msgInvalidSelfReg {
            get {
                return ResourceManager.GetString("msgInvalidSelfReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address length cannot exceed 255 char.
        /// </summary>
        public static string msgMxlSelfRegEmailAddress {
            get {
                return ResourceManager.GetString("msgMxlSelfRegEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email content..
        /// </summary>
        public static string msgReqEmailContent {
            get {
                return ResourceManager.GetString("msgReqEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email subject..
        /// </summary>
        public static string msgReqEmailSubject {
            get {
                return ResourceManager.GetString("msgReqEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter from email.
        /// </summary>
        public static string msgReqFromEmail {
            get {
                return ResourceManager.GetString("msgReqFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter help content.
        /// </summary>
        public static string msgReqHelpContent {
            get {
                return ResourceManager.GetString("msgReqHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address.
        /// </summary>
        public static string msgReqSelfRegEmailAddress {
            get {
                return ResourceManager.GetString("msgReqSelfRegEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid max length (&lt;=2000).
        /// </summary>
        public static string msgRngProfileMaxLength {
            get {
                return ResourceManager.GetString("msgRngProfileMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one group name..
        /// </summary>
        public static string msgSelectGroupName {
            get {
                return ResourceManager.GetString("msgSelectGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one user name..
        /// </summary>
        public static string msgSelectUserName {
            get {
                return ResourceManager.GetString("msgSelectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists.
        /// </summary>
        public static string msgSelfRegEmailExists {
            get {
                return ResourceManager.GetString("msgSelfRegEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the first name.
        /// </summary>
        public static string msgSelfRegFirstName {
            get {
                return ResourceManager.GetString("msgSelfRegFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the last name.
        /// </summary>
        public static string msgSelfRegLastName {
            get {
                return ResourceManager.GetString("msgSelfRegLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for submitting your details.
        /// </summary>
        public static string msgSelfRegSubmit {
            get {
                return ResourceManager.GetString("msgSelfRegSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile max length must be numbers only..
        /// </summary>
        public static string msgStrProfileMaxLengthNumeric {
            get {
                return ResourceManager.GetString("msgStrProfileMaxLengthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string msgValidSelfRegEmailAddress {
            get {
                return ResourceManager.GetString("msgValidSelfRegEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter profile title.
        /// </summary>
        public static string reqProfileTitle {
            get {
                return ResourceManager.GetString("reqProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter profile value.
        /// </summary>
        public static string reqProfileValuesTitle {
            get {
                return ResourceManager.GetString("reqProfileValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string thEmailIsOn {
            get {
                return ResourceManager.GetString("thEmailIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by.
        /// </summary>
        public static string thEmailModifiedby {
            get {
                return ResourceManager.GetString("thEmailModifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified date.
        /// </summary>
        public static string thEmailModifiedDate {
            get {
                return ResourceManager.GetString("thEmailModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email name.
        /// </summary>
        public static string thEmailName {
            get {
                return ResourceManager.GetString("thEmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string thEmailSubject {
            get {
                return ResourceManager.GetString("thEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From email.
        /// </summary>
        public static string thFromEmail {
            get {
                return ResourceManager.GetString("thFromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module title.
        /// </summary>
        public static string thHelpModule {
            get {
                return ResourceManager.GetString("thHelpModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string thHelpModuleParent {
            get {
                return ResourceManager.GetString("thHelpModuleParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string thIsDisplay {
            get {
                return ResourceManager.GetString("thIsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string thIsMandatory {
            get {
                return ResourceManager.GetString("thIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string thLanguage {
            get {
                return ResourceManager.GetString("thLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLength.
        /// </summary>
        public static string thmaxLength {
            get {
                return ResourceManager.GetString("thmaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string thOrganisation {
            get {
                return ResourceManager.GetString("thOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Option.
        /// </summary>
        public static string thProfileOptions {
            get {
                return ResourceManager.GetString("thProfileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Title.
        /// </summary>
        public static string thProfileTitle {
            get {
                return ResourceManager.GetString("thProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string thProfileType {
            get {
                return ResourceManager.GetString("thProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile values.
        /// </summary>
        public static string thProfileValues {
            get {
                return ResourceManager.GetString("thProfileValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string thSelfRegEmail {
            get {
                return ResourceManager.GetString("thSelfRegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string thSelfRegFirstName {
            get {
                return ResourceManager.GetString("thSelfRegFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string thSelfRegLastName {
            get {
                return ResourceManager.GetString("thSelfRegLastName", resourceCulture);
            }
        }
    }
}
