//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active users.
        /// </summary>
        public static string lblActiveUsers {
            get {
                return ResourceManager.GetString("lblActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string lblAnd {
            get {
                return ResourceManager.GetString("lblAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string lblApril {
            get {
                return ResourceManager.GetString("lblApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string lblAssignment {
            get {
                return ResourceManager.GetString("lblAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string lblAssignments {
            get {
                return ResourceManager.GetString("lblAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of attempted courses.
        /// </summary>
        public static string lblAtemptedCourses {
            get {
                return ResourceManager.GetString("lblAtemptedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string lblAugust {
            get {
                return ResourceManager.GetString("lblAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average marks obtained.
        /// </summary>
        public static string lblAvgMarks {
            get {
                return ResourceManager.GetString("lblAvgMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string lblCompleted {
            get {
                return ResourceManager.GetString("lblCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed courses.
        /// </summary>
        public static string lblCompletedCourse {
            get {
                return ResourceManager.GetString("lblCompletedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Status Detail.
        /// </summary>
        public static string lblCourseStatusDetail {
            get {
                return ResourceManager.GetString("lblCourseStatusDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string lblDecember {
            get {
                return ResourceManager.GetString("lblDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export in excel.
        /// </summary>
        public static string lblExportinexcel {
            get {
                return ResourceManager.GetString("lblExportinexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export in pdf.
        /// </summary>
        public static string lblExportinPDF {
            get {
                return ResourceManager.GetString("lblExportinPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string lblFebruary {
            get {
                return ResourceManager.GetString("lblFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblGenerateReport {
            get {
                return ResourceManager.GetString("lblGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string lblHours {
            get {
                return ResourceManager.GetString("lblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Completed.
        /// </summary>
        public static string lblInCompleted {
            get {
                return ResourceManager.GetString("lblInCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string lblInProgress {
            get {
                return ResourceManager.GetString("lblInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string lblJanuary {
            get {
                return ResourceManager.GetString("lblJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string lblJuly {
            get {
                return ResourceManager.GetString("lblJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string lblJune {
            get {
                return ResourceManager.GetString("lblJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string lblMarch {
            get {
                return ResourceManager.GetString("lblMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string lblMay {
            get {
                return ResourceManager.GetString("lblMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string lblMinutes {
            get {
                return ResourceManager.GetString("lblMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never logged in.
        /// </summary>
        public static string lblNeverLoginUsers {
            get {
                return ResourceManager.GetString("lblNeverLoginUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of courses.
        /// </summary>
        public static string lblNoOfCourses {
            get {
                return ResourceManager.GetString("lblNoOfCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string lblNotStarted {
            get {
                return ResourceManager.GetString("lblNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string lblNovember {
            get {
                return ResourceManager.GetString("lblNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string lblOctober {
            get {
                return ResourceManager.GetString("lblOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation group user detail.
        /// </summary>
        public static string lblOrganisationGroupUserDetail {
            get {
                return ResourceManager.GetString("lblOrganisationGroupUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Licence Report.
        /// </summary>
        public static string lblOrganisationLicenceReport {
            get {
                return ResourceManager.GetString("lblOrganisationLicenceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation User Report.
        /// </summary>
        public static string lblOrganisationUserReport {
            get {
                return ResourceManager.GetString("lblOrganisationUserReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent home page.
        /// </summary>
        public static string lblParentHomePage {
            get {
                return ResourceManager.GetString("lblParentHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string lblSeptember {
            get {
                return ResourceManager.GetString("lblSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Home page.
        /// </summary>
        public static string lblTeacherHomePage {
            get {
                return ResourceManager.GetString("lblTeacherHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Dropdown.
        /// </summary>
        public static string lblToggleDropdown {
            get {
                return ResourceManager.GetString("lblToggleDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total active users.
        /// </summary>
        public static string lblTotalActiveusers {
            get {
                return ResourceManager.GetString("lblTotalActiveusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Assignments.
        /// </summary>
        public static string lblTotalAssignments {
            get {
                return ResourceManager.GetString("lblTotalAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total subjects.
        /// </summary>
        public static string lblTotalCategories {
            get {
                return ResourceManager.GetString("lblTotalCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total courses.
        /// </summary>
        public static string lblTotalCourses {
            get {
                return ResourceManager.GetString("lblTotalCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total groups.
        /// </summary>
        public static string lblTotalGroups {
            get {
                return ResourceManager.GetString("lblTotalGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total organisations.
        /// </summary>
        public static string lblTotalOrganisation {
            get {
                return ResourceManager.GetString("lblTotalOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time spent.
        /// </summary>
        public static string lblTotalTimeSpent {
            get {
                return ResourceManager.GetString("lblTotalTimeSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users course passed.
        /// </summary>
        public static string lblTotalUserCoursePassPercentage {
            get {
                return ResourceManager.GetString("lblTotalUserCoursePassPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users registered.
        /// </summary>
        public static string lblTotalUserCourseRegistered {
            get {
                return ResourceManager.GetString("lblTotalUserCourseRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string lblTotalUsers {
            get {
                return ResourceManager.GetString("lblTotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string thAssigned {
            get {
                return ResourceManager.GetString("thAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string thCategory {
            get {
                return ResourceManager.GetString("thCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string thCompleted {
            get {
                return ResourceManager.GetString("thCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        public static string thCompletionDate {
            get {
                return ResourceManager.GetString("thCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string thCourse {
            get {
                return ResourceManager.GetString("thCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course user Detail.
        /// </summary>
        public static string thCourseUserDetail {
            get {
                return ResourceManager.GetString("thCourseUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string thEmail {
            get {
                return ResourceManager.GetString("thEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id.
        /// </summary>
        public static string thEmployeeId {
            get {
                return ResourceManager.GetString("thEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string thExpiryDate {
            get {
                return ResourceManager.GetString("thExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string thFirstname {
            get {
                return ResourceManager.GetString("thFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string thIncomplete {
            get {
                return ResourceManager.GetString("thIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string thLastName {
            get {
                return ResourceManager.GetString("thLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string thNotStarted {
            get {
                return ResourceManager.GetString("thNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string thNumber {
            get {
                return ResourceManager.GetString("thNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string thOrganisation {
            get {
                return ResourceManager.GetString("thOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Group Detail.
        /// </summary>
        public static string thOrganisationGroupDetail {
            get {
                return ResourceManager.GetString("thOrganisationGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string ThPercent {
            get {
                return ResourceManager.GetString("ThPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string thRegistrationDate {
            get {
                return ResourceManager.GetString("thRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score (%).
        /// </summary>
        public static string thScore {
            get {
                return ResourceManager.GetString("thScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string thStatus {
            get {
                return ResourceManager.GetString("thStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User course detail.
        /// </summary>
        public static string thUserCourseDetail {
            get {
                return ResourceManager.GetString("thUserCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Detail.
        /// </summary>
        public static string thUserDetail {
            get {
                return ResourceManager.GetString("thUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation user report.
        /// </summary>
        public static string tooltipOrganisationUserReport {
            get {
                return ResourceManager.GetString("tooltipOrganisationUserReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assessment report.
        /// </summary>
        public static string tooltipUserAssesmentReport {
            get {
                return ResourceManager.GetString("tooltipUserAssesmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assessment detail.
        /// </summary>
        public static string tooltipUserAssessmentDetail {
            get {
                return ResourceManager.GetString("tooltipUserAssessmentDetail", resourceCulture);
            }
        }
    }
}
