//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSResourse.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSResourse.Admin.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string btnAddUser {
            get {
                return ResourceManager.GetString("btnAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and add another.
        /// </summary>
        public static string btnAddUserOption1 {
            get {
                return ResourceManager.GetString("btnAddUserOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string btnConfirmDelete {
            get {
                return ResourceManager.GetString("btnConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string btnGeneratePassword {
            get {
                return ResourceManager.GetString("btnGeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Users.
        /// </summary>
        public static string btnImportUser {
            get {
                return ResourceManager.GetString("btnImportUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save record.
        /// </summary>
        public static string btnSaveAssignment {
            get {
                return ResourceManager.GetString("btnSaveAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string fldConfirmPassword {
            get {
                return ResourceManager.GetString("fldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number.
        /// </summary>
        public static string fldContactNo {
            get {
                return ResourceManager.GetString("fldContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string fldDesignation {
            get {
                return ResourceManager.GetString("fldDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string fldEmailAddress {
            get {
                return ResourceManager.GetString("fldEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id.
        /// </summary>
        public static string fldEmployeeId {
            get {
                return ResourceManager.GetString("fldEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry within next 30 days.
        /// </summary>
        public static string fldExpiry {
            get {
                return ResourceManager.GetString("fldExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string fldfile {
            get {
                return ResourceManager.GetString("fldfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string fldFirstName {
            get {
                return ResourceManager.GetString("fldFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string fldGroups {
            get {
                return ResourceManager.GetString("fldGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string fldLastName {
            get {
                return ResourceManager.GetString("fldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager&apos;s name.
        /// </summary>
        public static string fldManagerName {
            get {
                return ResourceManager.GetString("fldManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option1.
        /// </summary>
        public static string fldOption1 {
            get {
                return ResourceManager.GetString("fldOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option2.
        /// </summary>
        public static string fldOption2 {
            get {
                return ResourceManager.GetString("fldOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string fldOrganisation {
            get {
                return ResourceManager.GetString("fldOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string fldPassword {
            get {
                return ResourceManager.GetString("fldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string fldRoles {
            get {
                return ResourceManager.GetString("fldRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string fldStatus {
            get {
                return ResourceManager.GetString("fldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string fldUserName {
            get {
                return ResourceManager.GetString("fldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user?.
        /// </summary>
        public static string lblConfirmDeleteHeading {
            get {
                return ResourceManager.GetString("lblConfirmDeleteHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string lblMeghaBite {
            get {
                return ResourceManager.GetString("lblMeghaBite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Courses.
        /// </summary>
        public static string lblResetCourses {
            get {
                return ResourceManager.GetString("lblResetCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 8 characters long.
        /// </summary>
        public static string Msg8Char {
            get {
                return ResourceManager.GetString("Msg8Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected user?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient rights to delete the user..
        /// </summary>
        public static string msgDelete_User_NotValidRights {
            get {
                return ResourceManager.GetString("msgDelete_User_NotValidRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit.
        /// </summary>
        public static string MsgDigit {
            get {
                return ResourceManager.GetString("MsgDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exist.
        /// </summary>
        public static string msgDupEmailAddress {
            get {
                return ResourceManager.GetString("msgDupEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id already exist.
        /// </summary>
        public static string msgDupEmployeeid {
            get {
                return ResourceManager.GetString("msgDupEmployeeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist.
        /// </summary>
        public static string msgDupUserName {
            get {
                return ResourceManager.GetString("msgDupUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not exists.
        /// </summary>
        public static string msgEmailNotExists {
            get {
                return ResourceManager.GetString("msgEmailNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password should be match.
        /// </summary>
        public static string msgErrorCnfPassword {
            get {
                return ResourceManager.GetString("msgErrorCnfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload file of type: .xls.
        /// </summary>
        public static string msgErrorExcel {
            get {
                return ResourceManager.GetString("msgErrorExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is too large, maximum allowed size is :.
        /// </summary>
        public static string msgErrorFileTooLarge {
            get {
                return ResourceManager.GetString("msgErrorFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select date for.
        /// </summary>
        public static string msgErrorSelectdata {
            get {
                return ResourceManager.GetString("msgErrorSelectdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Duplicate UserName. .
        /// </summary>
        public static string msgImpDupUserName {
            get {
                return ResourceManager.GetString("msgImpDupUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing..
        /// </summary>
        public static string msgImpFldMissing {
            get {
                return ResourceManager.GetString("msgImpFldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect field value. .
        /// </summary>
        public static string msgImpFmt {
            get {
                return ResourceManager.GetString("msgImpFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not in valid format.
        /// </summary>
        public static string msgImpFmtFile {
            get {
                return ResourceManager.GetString("msgImpFmtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid import file. Supported format is .xls.
        /// </summary>
        public static string msgImpFmtFileExt {
            get {
                return ResourceManager.GetString("msgImpFmtFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group missing..
        /// </summary>
        public static string msgImpGroup {
            get {
                return ResourceManager.GetString("msgImpGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Group.
        /// </summary>
        public static string msgImpInvalidGroup {
            get {
                return ResourceManager.GetString("msgImpInvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Organisation..
        /// </summary>
        public static string msgImpInvalidOrganisation {
            get {
                return ResourceManager.GetString("msgImpInvalidOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role..
        /// </summary>
        public static string msgImpInvalidRole {
            get {
                return ResourceManager.GetString("msgImpInvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive missing..
        /// </summary>
        public static string msgImpIsActive {
            get {
                return ResourceManager.GetString("msgImpIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation missing..
        /// </summary>
        public static string msgImpOrganisation {
            get {
                return ResourceManager.GetString("msgImpOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Created.
        /// </summary>
        public static string msgImpRecStatusCr {
            get {
                return ResourceManager.GetString("msgImpRecStatusCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in record.
        /// </summary>
        public static string msgImpRecStatusErr {
            get {
                return ResourceManager.GetString("msgImpRecStatusErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated.
        /// </summary>
        public static string msgImpRecStatusUp {
            get {
                return ResourceManager.GetString("msgImpRecStatusUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  columns not exist in excel file.
        /// </summary>
        public static string msgImpReqCol {
            get {
                return ResourceManager.GetString("msgImpReqCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email missing. .
        /// </summary>
        public static string msgImpReqEmail {
            get {
                return ResourceManager.GetString("msgImpReqEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname missing..
        /// </summary>
        public static string msgImpReqFirstName {
            get {
                return ResourceManager.GetString("msgImpReqFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname missing..
        /// </summary>
        public static string msgImpReqLastName {
            get {
                return ResourceManager.GetString("msgImpReqLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role missing..
        /// </summary>
        public static string msgImpRole {
            get {
                return ResourceManager.GetString("msgImpRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sheet name in uploaded import file. Sheet name should be among the ImportUsers, ExportUserSheet or Sheet1..
        /// </summary>
        public static string msgInvalidSheetName {
            get {
                return ResourceManager.GetString("msgInvalidSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.	Record(s) successfully processed:.
        /// </summary>
        public static string msgLbla {
            get {
                return ResourceManager.GetString("msgLbla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.	Created record(s):.
        /// </summary>
        public static string msgLblb {
            get {
                return ResourceManager.GetString("msgLblb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.	Updated record(s):.
        /// </summary>
        public static string msgLblc {
            get {
                return ResourceManager.GetString("msgLblc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.	Failed record(s):.
        /// </summary>
        public static string msgLbld {
            get {
                return ResourceManager.GetString("msgLbld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create user due to exceeded organisation limit or organisation expired..
        /// </summary>
        public static string msgLicenceUserExceed {
            get {
                return ResourceManager.GetString("msgLicenceUserExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase character.
        /// </summary>
        public static string msgLower {
            get {
                return ResourceManager.GetString("msgLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create user due to exceeded no of max user of selected group..
        /// </summary>
        public static string msgMaxUserExceed {
            get {
                return ResourceManager.GetString("msgMaxUserExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        public static string msgMinCnfPassword {
            get {
                return ResourceManager.GetString("msgMinCnfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        public static string msgMinPassword {
            get {
                return ResourceManager.GetString("msgMinPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email length cannot exceed 250 char.
        /// </summary>
        public static string msgMxlEmail {
            get {
                return ResourceManager.GetString("msgMxlEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address length cannot exceed 255 char.
        /// </summary>
        public static string msgMxlEmailAddress {
            get {
                return ResourceManager.GetString("msgMxlEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id length cannot exceed 50 char.
        /// </summary>
        public static string msgMxlEmployeeId {
            get {
                return ResourceManager.GetString("msgMxlEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name length cannot exceed 150 char.
        /// </summary>
        public static string msgMxlFirstName {
            get {
                return ResourceManager.GetString("msgMxlFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name length cannot exceed 150 char.
        /// </summary>
        public static string msgMxlLastName {
            get {
                return ResourceManager.GetString("msgMxlLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address.
        /// </summary>
        public static string msgReqEmailAddress {
            get {
                return ResourceManager.GetString("msgReqEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter employee id.
        /// </summary>
        public static string msgReqEmployeeId {
            get {
                return ResourceManager.GetString("msgReqEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload file.
        /// </summary>
        public static string msgReqfile {
            get {
                return ResourceManager.GetString("msgReqfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name.
        /// </summary>
        public static string msgReqFirstName {
            get {
                return ResourceManager.GetString("msgReqFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name.
        /// </summary>
        public static string msgReqLastName {
            get {
                return ResourceManager.GetString("msgReqLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string msgReqOption_n_dropdown {
            get {
                return ResourceManager.GetString("msgReqOption_n_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter.
        /// </summary>
        public static string msgReqOption_n_text {
            get {
                return ResourceManager.GetString("msgReqOption_n_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select organisation.
        /// </summary>
        public static string msgReqOrganisation {
            get {
                return ResourceManager.GetString("msgReqOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one group.
        /// </summary>
        public static string msgReqUserGroup {
            get {
                return ResourceManager.GetString("msgReqUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one user role.
        /// </summary>
        public static string msgReqUserRoles {
            get {
                return ResourceManager.GetString("msgReqUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset selected course(s)?.
        /// </summary>
        public static string msgResetCourses {
            get {
                return ResourceManager.GetString("msgResetCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected course(s) have been reset.
        /// </summary>
        public static string msgResetSuccess {
            get {
                return ResourceManager.GetString("msgResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one user.
        /// </summary>
        public static string msgSelfRegSelectUser {
            get {
                return ResourceManager.GetString("msgSelfRegSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric character.
        /// </summary>
        public static string MsgSpecial {
            get {
                return ResourceManager.GetString("MsgSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update user due to exceeded no of max user of selected group..
        /// </summary>
        public static string msgUpdateMaxUserExceed {
            get {
                return ResourceManager.GetString("msgUpdateMaxUserExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase character.
        /// </summary>
        public static string MsgUpper {
            get {
                return ResourceManager.GetString("MsgUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string msgValidEmailAddress {
            get {
                return ResourceManager.GetString("msgValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string thAssignedCourseAssignStatus {
            get {
                return ResourceManager.GetString("thAssignedCourseAssignStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string thAssignedCourseCategory {
            get {
                return ResourceManager.GetString("thAssignedCourseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string thAssignedCourseCertificate {
            get {
                return ResourceManager.GetString("thAssignedCourseCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        public static string thAssignedCourseExpiryDate {
            get {
                return ResourceManager.GetString("thAssignedCourseExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string thAssignedCourseName {
            get {
                return ResourceManager.GetString("thAssignedCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string thAssignedCourseReset {
            get {
                return ResourceManager.GetString("thAssignedCourseReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string thEmailAddress {
            get {
                return ResourceManager.GetString("thEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee id.
        /// </summary>
        public static string thEmployeeId {
            get {
                return ResourceManager.GetString("thEmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string thFirstName {
            get {
                return ResourceManager.GetString("thFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string thGroups {
            get {
                return ResourceManager.GetString("thGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string thLastName {
            get {
                return ResourceManager.GetString("thLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login date.
        /// </summary>
        public static string thLoginDate {
            get {
                return ResourceManager.GetString("thLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string thOrganisation {
            get {
                return ResourceManager.GetString("thOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string thRegistrationDate {
            get {
                return ResourceManager.GetString("thRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string thRoles {
            get {
                return ResourceManager.GetString("thRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string thStatus {
            get {
                return ResourceManager.GetString("thStatus", resourceCulture);
            }
        }
    }
}
