//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryInfo
    {
        public long CategoryInfoId { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public int LanguageId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatedById { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<long> LastModifiedById { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
    }
}
