//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryInfoes = new HashSet<CategoryInfo>();
            this.Courses = new HashSet<Course>();
            this.DocumentManagers = new HashSet<DocumentManager>();
            this.Topics = new HashSet<Topic>();
            this.Quizes = new HashSet<Quize>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatedById { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<long> LastModifiedById { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteInformation { get; set; }
    
        public virtual ICollection<CategoryInfo> CategoryInfoes { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<DocumentManager> DocumentManagers { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<Quize> Quizes { get; set; }
    }
}
