//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.course_state = new HashSet<course_state>();
            this.CourseUnits = new HashSet<CourseUnit>();
            this.CourseInfoes = new HashSet<CourseInfo>();
            this.GroupCourses = new HashSet<GroupCourse>();
            this.UserCourses = new HashSet<UserCourse>();
            this.UserCourseRequests = new HashSet<UserCourseRequest>();
            this.TopicUnits = new HashSet<TopicUnit>();
        }
    
        public long CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CourseDescription { get; set; }
        public Nullable<int> CertificateId { get; set; }
        public string FolderLocation { get; set; }
        public string LaunchFileName { get; set; }
        public Nullable<long> FileSizeInKB { get; set; }
        public string ScoLabel { get; set; }
        public Nullable<bool> IsFinalized { get; set; }
        public Nullable<int> WindowWidth { get; set; }
        public Nullable<int> WindowHeight { get; set; }
        public bool BottomNavigation { get; set; }
        public bool LeftNavigation { get; set; }
        public bool TopContent { get; set; }
        public Nullable<int> PassMarks { get; set; }
        public Nullable<bool> IsUserDefined { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<long> LastModifiedById { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteInformation { get; set; }
        public Nullable<int> CourseType { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> Mandaotry { get; set; }
        public Nullable<int> CourseDurationMin { get; set; }
        public Nullable<int> CourseFees { get; set; }
        public Nullable<byte> FeeType { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public string Tags { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Certificate Certificate { get; set; }
        public virtual ICollection<course_state> course_state { get; set; }
        public virtual ICollection<CourseUnit> CourseUnits { get; set; }
        public virtual ICollection<CourseInfo> CourseInfoes { get; set; }
        public virtual ICollection<GroupCourse> GroupCourses { get; set; }
        public virtual ICollection<UserCourse> UserCourses { get; set; }
        public virtual ICollection<UserCourseRequest> UserCourseRequests { get; set; }
        public virtual ICollection<TopicUnit> TopicUnits { get; set; }
    }
}
