//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.DistrictBlocks = new HashSet<DistrictBlock>();
        }
    
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<DistrictBlock> DistrictBlocks { get; set; }
    }
}
