//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictSchool
    {
        public int SchoolId { get; set; }
        public int BlockId { get; set; }
        public string Scode { get; set; }
        public string SchoolName { get; set; }
        public string Location { get; set; }
        public string Udise { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalMobile { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual DistrictBlock DistrictBlock { get; set; }
    }
}
