//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictBlock
    {
        public DistrictBlock()
        {
            this.DistrictSchools = new HashSet<DistrictSchool>();
        }
    
        public int BlockId { get; set; }
        public string BlockName { get; set; }
        public int DistrictId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<DistrictSchool> DistrictSchools { get; set; }
    }
}
