//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupInfo
    {
        public long GroupInfoId { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupManager { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNo { get; set; }
        public int LanguageId { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<long> LastModifiedByID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Language Language { get; set; }
    }
}
