//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationInfo
    {
        public long OrganisationInfoId { get; set; }
        public int OrganisationID { get; set; }
        public string OrganisationUID { get; set; }
        public string OrganisationName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int LanguageId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatedById { get; set; }
        public Nullable<long> LastModifiedByID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string OrganisationLogo { get; set; }
        public string OrganisationBanner { get; set; }
        public string AddressLine3 { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
