//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.Groups = new HashSet<Group>();
            this.Licenses = new HashSet<License>();
            this.OrganisationInfoes = new HashSet<OrganisationInfo>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.UserProfileSettingsOrgs = new HashSet<UserProfileSettingsOrg>();
        }
    
        public int OrganisationID { get; set; }
        public string OrganisationName { get; set; }
        public string OrganisationUID { get; set; }
        public bool Status { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatedById { get; set; }
        public Nullable<long> LastModifiedByID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteInformation { get; set; }
        public string OrganisationLogo { get; set; }
        public string OrganisationBanner { get; set; }
        public string AddressLine3 { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public long MaxUsers { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool IsUserAssignment { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
        public virtual ICollection<OrganisationInfo> OrganisationInfoes { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UserProfileSettingsOrg> UserProfileSettingsOrgs { get; set; }
    }
}
