//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.EmailLogs = new HashSet<EmailLog>();
            this.ParentStudents = new HashSet<ParentStudent>();
            this.SupportInfoes = new HashSet<SupportInfo>();
            this.UserCourses = new HashSet<UserCourse>();
            this.UserCourseRequests = new HashSet<UserCourseRequest>();
            this.UserDocuments = new HashSet<UserDocument>();
            this.UserDocumentHits = new HashSet<UserDocumentHit>();
            this.UserGroups = new HashSet<UserGroup>();
            this.UserLogins = new HashSet<UserLogin>();
            this.UserQuizs = new HashSet<UserQuiz>();
            this.UserQuizRecords = new HashSet<UserQuizRecord>();
            this.UserQuizScores = new HashSet<UserQuizScore>();
            this.UserScheduledEvents = new HashSet<UserScheduledEvent>();
        }
    
        public long UserId { get; set; }
        public string Id { get; set; }
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNo { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public bool Status { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public Nullable<long> LastModifiedByID { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public bool IsPasswordChanged { get; set; }
        public bool IsRegisterMailSend { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public bool IsDelete { get; set; }
        public string DeleteInformation { get; set; }
        public string Designation { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<ParentStudent> ParentStudents { get; set; }
        public virtual ICollection<SupportInfo> SupportInfoes { get; set; }
        public virtual ICollection<UserCourse> UserCourses { get; set; }
        public virtual ICollection<UserCourseRequest> UserCourseRequests { get; set; }
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
        public virtual ICollection<UserDocumentHit> UserDocumentHits { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<UserQuiz> UserQuizs { get; set; }
        public virtual ICollection<UserQuizRecord> UserQuizRecords { get; set; }
        public virtual ICollection<UserQuizScore> UserQuizScores { get; set; }
        public virtual ICollection<UserScheduledEvent> UserScheduledEvents { get; set; }
    }
}
