//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLSLms
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileSettingsInfo
    {
        public int ID { get; set; }
        public int ProfileSettignOrgId { get; set; }
        public string ProfileTitle { get; set; }
        public int LanguageID { get; set; }
        public long LastModifiedByID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual UserProfileSettingsOrg UserProfileSettingsOrg { get; set; }
    }
}
